### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by gorkem** [fabric8-analytics/vscode-osio-auth#20]
An extension needs an icon that will be displayed on the 
marketplace and inside the vscode's extension screen.

**Comment by invincibleJai** [comment]
@gorkem yes we need have it , We have it as open item in task list https://github.com/openshiftio/openshift.io/issues/1455

icon is not finalised, for now till we get it decided am planning to have OSIO icon

**Comment by invincibleJai** [comment]
Have received the icons and updated.
