### ISSUE TITLE
Error while authorizing OSIO

### ISSUE THREAD

**Issue by sivaavkd** [fabric8-analytics/vscode-osio-auth#22]
VSCode Version 1.19.1 - on MacBook Pro (15-inch, 2016) MacOS HighSierra 10.13.2 (17C88)

![vscode error](https://user-images.githubusercontent.com/32661994/34599015-561f12e0-f216-11e7-8f3f-d3bef301ca54.png)

**Comment by sara-02** [comment]
+1 
For me the version is 1.19.0
OS: Fedora 25

**Comment by sara-02** [comment]
Seems to work for me now. Thanks @invincibleJai 
But, since the last error was checked, my OS has been updated.
Current configurations are:
OS: Fedora 27
VSCode: 1.19.1

**Comment by invincibleJai** [comment]
Issue has been fixed hence closing , pls reopen if feel otherwise.
