### ISSUE TITLE
Improve disable plugin info message.

### ISSUE THREAD

**Issue by sara-02** [fabric8-analytics/vscode-osio-auth#23]
When the auth plugin is disabled, and the ide is reloaded, the messages see is 
`info: Looks like your extension is not authorized, kindly authorize with OSIO`
If the plugin is disabled, the first message should something like:
`info: Auth plugin diabled, enable it to run stack analysis`

Step 1:
![screenshot from 2018-01-05 12-43-41](https://user-images.githubusercontent.com/7047079/34599047-789637b8-f216-11e7-947c-84e10e6059a0.png)

Step2:
![screenshot from 2018-01-05 12-52-43](https://user-images.githubusercontent.com/7047079/34599291-5fd40858-f217-11e7-8bbf-1cafaef7ac83.png)

Version: 1.19.0
OS: Fedora 25

**Comment by invincibleJai** [comment]
@sara-02 what i can see u did disable one extension that is OSIO-AUTH not f8-analytics that is the reason this notification appears.

As per my understanding if you disable both extension you won't get any notification.

Closing it , pls feel free to reopen.
